# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.15.0

pipelines:
  branches:
    "staging":
      - step:
          name: FE - Build and deploy
          deployment: Staging
          caches:
            - node
          script:
            - npm install --silent
            - CI=false npm run build:staging
            - pipe: atlassian/aws-s3-deploy:0.3.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'ap-southeast-2'
                S3_BUCKET: $S3_BUCKET
                LOCAL_PATH: '$BITBUCKET_CLONE_DIR/build'
                ACL: 'public-read'
                DELETE_FLAG: 'true'
            - pipe: atlassian/aws-cloudfront-invalidate:0.1.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'ap-southeast-2'
                DISTRIBUTION_ID: $CLOUDFRONT_DISTRIBUTION_ID
    "master":
      - step:
          name: FE - Build and deploy
          deployment: Production
          caches:
            - node
          script:
            - npm install --silent
            - CI=false npm run build
            - pipe: atlassian/aws-s3-deploy:0.3.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'ap-southeast-2'
                S3_BUCKET: $S3_BUCKET
                LOCAL_PATH: '$BITBUCKET_CLONE_DIR/build'
                ACL: 'public-read'
                DELETE_FLAG: 'true'
            - pipe: atlassian/aws-cloudfront-invalidate:0.1.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'ap-southeast-2'
                DISTRIBUTION_ID: $CLOUDFRONT_DISTRIBUTION_ID
